export default class MapleMaps {
    maps = [
        // Vanishing Journey
        "Weathered Land of Happiness",
        "Weathered Land of Happiness and Rage",
        "Weathered Land of Rage",
        "Weathered Land of Rage and Sorrow",
        "Weathered Land of Sorrow",
        "Weathered Land of Sorrow and Joy",
        "Weathered Land of Joy",
        "Rock Zone",
        "Fire Rock Zone",
        "Fire Zone",
        "Fire Spirit Zone",
        "Spirit Zone",
        "Forked Road 1",
        "Western Cave Path 1",
        "Western Cave Path 2",
        "Eastern Cave Path 1",
        "Eastern Cave Path 2",
        "Forked Road 2",
        "Below the Cave",
        "Above the Cave",
        "Cave Depths",
        "Split Road of Destiny",
        "Arma's Hideout",
        "Hidden Lakeshore",
        "Hidden Fire Zone",
        "Hidden Cave",
        // Reverse City
        "Subway Tunnel 1",
        "Subway Tunnel 2",
        "Subway Tunnel 3",
        "Subway Tunnel 4",
        "Subway Tunnel 5",
        "Subway Tunnel 6",
        "T-Boy's Research Train 1",
        "T-Boy's Research Train 2",
        "T-Boy's Research Train 3",
        "Underground Train 1",
        "Underground Train 2",
        "Underground Train 3",
        "Surface Train 1",
        "Surface Train 2",
        "Surface Train 3",
        "M Tower 2",
        "M Tower 3",
        "M Tower 4",
        "Hidden Research Train",
        "Hidden Underground Train",
        "Hidden M Tower",
        // Chu Chu Island
        "Hill Path",
        "Mottled Forest 1",
        "Mottled Forest 2",
        "Mottled Forest 3",
        "Within Five-Color Hill",
        "Dealie-Bobber Forest 1",
        "Dealie-Bobber Forest 2",
        "Bitty-Bobble Forest 1",
        "Bitty-Bobble Forest 2",
        "Slurpy Forest Depths",
        "Torrent Zone 1",
        "Torrent Zone 2",
        "Torrent Zone 3",
        "Below the Falls",
        "Mountain's Mouth",
        "Skywhale Mountainside 1",
        "Skywhale Mountainside 2",
        "Skywhale Peak",
        "Colossal Tail",
        // Yum Yum Island
        "Mushbud Forest 1",
        "Mushbud Forest 2",
        "Mushbud Forest 3",
        "Mushbud Forest 4",
        "Mushbud Forest 5",
        "Mushbud Forest 6",
        "Illiard Field 1",
        "Illiard Field 2",
        "Illiard Field 3",
        "Illiard Field 4",
        "Illiard Field 5",
        "Illiard Field 6",
        "Fungos Forest 1",
        "Fungos Forest 2",
        "Fungos Forest 3",
        "Fungos Forest 4",
        "Fungos Forest 5",
        "Fungos Forest 6",
        "Hidden Mushbud Forest",
        "Hidden Illiard Field",
        "Hidden Fungos Forest",
        // Arcana
        "The Forest of Water",
        "The Forest of Sunlight",
        "Where Water and Sunlight Meet",
        "The Forest of Earth",
        "Where Earth and Sunlight Meet",
        "Snow Cloud Clearing",
        "Thunder Cloud Clearing",
        "Between Frost and Thunder 1",
        "Between Frost and Thunder 2",
        "Forest of Toxins",
        "The Volatile Forest",
        "The Volatile and Toxic Forest 1",
        "The Volatile and Toxic Forest 2",
        "Cavern Upper Path",
        "Deep in the Cavern - Upper Path 1",
        "Deep in the Cavern - Upper Path 2",
        "The Deepest Part of the Cavern - Upper Path",
        "Cavern Lower Path",
        "Deep in the Cavern - Lower Path 1",
        "Deep in the Cavern - Lower Path 2",
        "The Deepest Part of the Cavern - Lower Path",
        "Labyrinthine Cavern",
        "Labyrinthine Cavern - Upper Path",
        "Labyrinthine Cavern - Side Path",
        "Labyrinthine Cavern - Lower Path",
        "Beneath the Spirit Tree",
        // Morass
        "Path to the Coral Forest 2",
        "Path to the Coral Forest 3",
        "Path to the Coral Forest 4",
        "Path to the Coral Forest 5",
        "Street Cat Area",
        "Street Cat Area 2",
        "Bully Blvd.",
        "Bully Blvd. 2",
        "Bully Blvd. 3",
        "Shadowdance Hall",
        "Shadowdance Hall 2",
        "Shadowdance Hall 3",
        "Shadowdance Hall 4",
        "Abandoned Area",
        "Abandoned Area 2",
        "Abandoned Area 3",
        "That Day in Trueffet 2",
        "That Day in Trueffet 3",
        "That Day in Trueffet 4",
        // Esfera
        "Living Spring 2",
        "Living Spring 3",
        "Living Spring 4",
        "Living Spring 5",
        "Living Spring 6",
        "Living Spring 7",
        "Mirror-touched Sea 2",
        "Mirror-touched Sea 3",
        "Mirror-touched Sea 4",
        "Mirror-touched Sea 5",
        "Mirror-touched Sea 6",
        "Mirror-touched Sea 7",
        "Radiant Temple 2",
        "Radiant Temple 3",
        "Radiant Temple 4",
        // Sellas
        "The Final Edge of Light 1",
        "The Final Edge of Light 2",
        "The Final Edge of Light 3",
        "The Final Edge of Light 4",
        "The Final Edge of Light 5",
        "The Final Edge of Light 6",
        "The Final Edge of Light 7",
        "The Final Edge of Light 8",
        "The Final Edge of Light 9",
        "Plunging Depths 1",
        "Plunging Depths 2",
        "Plunging Depths 3",
        "Plunging Depths 4",
        "Plunging Depths 5",
        "Plunging Depths 6",
        "Star-Swallowing Sea 1",
        "Star-Swallowing Sea 2",
        "Star-Swallowing Sea 3",
        "Star-Swallowing Sea 4",
        "Star-Swallowing Sea 5",
        "Star-Swallowing Sea 6",
        // Moonbridge
        "Last Horizon 1",
        "Last Horizon 2",
        "Last Horizon 3",
        "Last Horizon 4",
        "Last Horizon 5",
        "Last Horizon 6",
        "Mysterious Fog 1",
        "Mysterious Fog 2",
        "Mysterious Fog 3",
        "Mysterious Fog 4",
        "Mysterious Fog 5",
        "Mysterious Fog 6",
        "Void Current 1",
        "Void Current 2",
        "Void Current 3",
        "Void Current 4",
        "Void Current 5",
        "Void Current 6",
        // Labyrinth of Suffering
        "Labyrinth of Suffering Interior 3",
        "Labyrinth of Suffering Interior 2",
        "Labyrinth of Suffering Interior 1",
        "Labyrinth of Suffering Interior 4",
        "Labyrinth of Suffering Interior 5",
        "Labyrinth of Suffering Interior 6",
        "Labyrinth of Suffering Core 1",
        "Labyrinth of Suffering Core 2",
        "Labyrinth of Suffering Core 3",
        "Labyrinth of Suffering Core 4",
        "Labyrinth of Suffering Core 5",
        "Labyrinth of Suffering Core 6",
        "Labyrinth of Suffering Core 7",
        "Labyrinth of Suffering Deep Core 1",
        "Labyrinth of Suffering Deep Core 2",
        "Labyrinth of Suffering Deep Core 3",
        "Labyrinth of Suffering Deep Core 4",
        "Labyrinth of Suffering Deep Core 5",
        "Labyrinth of Suffering Deep Core 6",
        // Limina
        "World's Sorrow Depths 1",
        "World's Sorrow Depths 2",
        "World's Sorrow Depths 3",
        "World's Sorrow Midpoint 1",
        "World's Sorrow Midpoint 2",
        "World's Sorrow Midpoint 3",
        "End of the World 1-4",
        "End of the World 1-5",
        "End of the World 1-6",
        "End of the World 2-2",
        "End of the World 2-3",
        "End of the World 2-4",
        "End of the World 2-5",
        // Cernium
        "Rocky Overlook 1",
        "Rocky Overlook 2",
        "Rocky Overlook 3",
        "Rocky Overlook 4",
        "Cernium Western City Ramparts 1",
        "Cernium Western City Ramparts 2",
        "Cernium Western City Ramparts 3",
        "Cernium Eastern City Ramparts 1",
        "Cernium Eastern City Ramparts 2",
        "Cernium Eastern City Ramparts 3",
        "Royal Library Section 1",
        "Royal Library Section 2",
        "Royal Library Section 3",
        "Royal Library Section 4",
        "Royal Library Section 5",
        "Royal Library Section 6",
        // Burning Cernium
        "Burning Royal Library Section 1",
        "Burning Royal Library Section 2",
        "Burning Royal Library Section 3",
        "Burning Royal Library Section 4",
        "Burning Royal Library Section 5",
        "Burning Royal Library Section 6",
        "Western City Ramparts in Battle 1",
        "Western City Ramparts in Battle 2",
        "Western City Ramparts in Battle 3",
        "Western City Ramparts in Battle 4",
        "Eastern City Ramparts in Battle 1",
        "Eastern City Ramparts in Battle 2",
        "Eastern City Ramparts in Battle 3",
        "Eastern City Ramparts in Battle 4",
        "Eastern City Ramparts in Battle 5",
        "Eastern City Ramparts in Battle 6",
        // Hotel Arcus
        "Outlaw-Infested Wastes 1",
        "Outlaw-Infested Wastes 2",
        "Outlaw-Infested Wastes 3",
        "Outlaw-Infested Wastes 4",
        "Nostalgic Drive-in Theater 1",
        "Nostalgic Drive-in Theater 2",
        "Nostalgic Drive-in Theater 3",
        "Nostalgic Drive-in Theater 4",
        "Nostalgic Drive-in Theater 5",
        "Nostalgic Drive-in Theater 6",
        "Train with No Destination 1",
        "Train with No Destination 2",
        "Train with No Destination 3",
        "Train with No Destination 4",
        "Train with No Destination 5",
        "Train with No Destination 6",
    ];

    getMapOptions() {
        let innerHtml = "";
        for (let map of this.maps) {
            innerHtml += `<option value="${map}">\n`;
        }
        return innerHtml;
    }
}
